{{- if .Values.check.deployment.enabled }}
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: deployment
  namespace: {{ .Release.Namespace }}
spec:
  runInterval:  {{ .Values.check.deployment.runInterval }}
  timeout: {{ .Values.check.deployment.timeout }}
  podSpec:
    {{- if .Values.securityContext.enabled }}
    securityContext:
      runAsUser: {{ .Values.securityContext.runAsUser }}
      fsGroup: {{ .Values.securityContext.fsGroup }}
    {{- end}}
    containers:
    - name: deployment
      image: {{ .Values.check.deployment.image.repository }}:{{ .Values.check.deployment.image.tag }}
      imagePullPolicy: IfNotPresent
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
{{- range $key, $value := .Values.check.deployment.extraEnvs }}
        - name: {{ $key }}
          value: {{ $value | quote }}
{{- end }}
      resources:
        requests:
          cpu: 25m
          memory: 15Mi
        limits:
          cpu: 40m
{{- if .Values.securityContext.enabled }}
      securityContext:
        allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
        readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
{{- end}}
      restartPolicy: Never
    {{- if .Values.check.deployment.nodeSelector }}
    nodeSelector:
{{- toYaml .Values.check.deployment.nodeSelector | nindent 6 }}
    {{- end }}
    serviceAccountName: deployment-sa
    terminationGracePeriodSeconds: 60
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-check-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-service-role
subjects:
  - kind: ServiceAccount
    name: deployment-sa
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-service-role
rules:
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-sa
  namespace: {{ .Release.Namespace }}
{{- end }}
